### PR TITLE
#26 - Update the battle roster to show the same badge that's on the field

### PR DESCRIPTION
**Pull request by tenshi13**
attempt at issue #26

### CODE REVIEW

**Comment by tenshi13** [comment]
@Asuza please have a look and comment here if there's any issues

**Comment by Asuza** [comment]
I know the feeling, @tenshi13! Sorry there is so much friction getting started. I've been trying to improve it since I started working on the project and there's so much that's still not ideal.

I took a screenshot of what I see with the new badge. It looks like it's most of the way there. The shape is a little off, and it needs some space between the badge and the user name, but it's close!

Does it look this way for you as well?
Badge screenshot

**Comment by tenshi13** [comment]
@Asuza hey man, yeah definately it was off, i mistaken margin for padding, should be updated now,
it should look like this now 
image

**Comment by tenshi13** [comment]
on the topic, I'm doing the testing with the data generated via gamerunner/run-test-game.js locally,
I've hit some snags, question:
- how is public/js/game-engine.js generated? it doesn't seem to be in the repo code?
- a get request to /userInfo when I load the site fails also, and I see that that get handler is only included in server/OAuthGithub.js... is it we need some logic to fetch userInfo from local db if the github args are not supplied?

**Comment by tenshi13** [comment]
Also no worries man, I'm learning new stuff and I'm happy : D
the project can be improved over time, just gotta keep the motivation somehow ; D

**Comment by Asuza** [comment]
@tenshi13, I recently moved _game-engine.js_ from a static file to use the code from the ai-battle-engine repo instead. From the ai-battle-website repo, run the following:
```
npm install
npm run build
```
And it should be created for you.

In regards to the "/userInfo" path, it only gets the logged-in users's info, which requires Github, so it's okay that the route isn't active unless you've enabled the server to connect to Github to begin with. Of course, that interaction could be improved. That's basically how it's worked since I started fixing things.

**Comment by tenshi13** [comment]
awesome it works, thx for the merge ; D

**Pull request merged**
