### PR TITLE
Added Knex to manage Database Schema and Migrations.

### LINKED ISSUE #65: Add a simple database patching mechanism
Currently, making database changes to the production site requires manual intervention. Create a way for the server to automatically apply patches (if needed) before the web server starts.

This change would be helpful when it's time for #56 and #57 to go live.

### PR DESCRIPTION
**Pull request by jcfausto**
Added Knex to manage database schema and migrations. 

Now, every time the server starts it will check for pending migrations and will automatically apply them to the database (patch).

In order to modify the DB schema, it will be required to create a Knex migration so that Knex can apply any pending migration to the database once the server starts.

Also, the ability to rollback DB changes easily was added with this PR, since Knex provide rolling back features.

Resolves #65

### CODE REVIEW

**Comment by Asuza** [comment]
Thank you for the PR! This looks great. I'll test it out as soon as I can.

**Comment by Asuza** [comment]
I apologize for the delay. I attempted to test this today but my vagrant/virtualbox has quit working on me. I'll keep you posted.

**Comment by jcfausto** [comment]
Ok. No worries.

**Comment by Asuza** [comment]
This seems really cool, but I can't get it to work properly with connect-pg-simple. It continues to complain about `Failed to prune sessions: no PostgreSQL user name specified in startup packet` when starting the server with authentication enabled (`node server.js --pretend-auth-as=Oswin`).

**Pull request merged**
